### ISSUE TITLE
Multithreading Handler for stress testing

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#15]
Context: Before the workshop, we wanna make sure `cityio` does not crash. For that, we need to stress test it by creating multiple `Handler`s running in their own thread and listening to different tables.

I'll create tables `dungeonA`, `dungeonB`, and `dungeonC` to run a diversity indicator in each one of them.

**Comment by crisjf** [comment]
This just needs testing once `cityio` is up again. Otherwise, this should be working.

@RELNO see the example here:
https://cityscope.media.mit.edu/CS_Brix/examples.html#multiple-tables-simultaneously

**Comment by crisjf** [comment]
The `Diversity` indicator is not working, but we need `cityio` to be up to fix it (see #13 )

**Comment by RELNO** [comment]
@crisjf very very nice, thanks. So in practice, a module maker can now spawn a generic module to all tables at once, same overhead?

**Comment by crisjf** [comment]
yes! and all in the same python script.
