### ISSUE TITLE
Which license are we using?

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#2]
I noticed we currently have a `GNU General Public License`, is there a specific reason for that? shouldn't we be using the `MIT License`?

**Comment by crisjf** [comment]
From Ariel:

```
We agreed on gpl3 at the inception of CS Org. @Yasushi is the licenses Sensai, but in a nutshell, MIT itself don't approve MIT license..
```

**Comment by yasushisakai** [comment]
MIT endorses GPL v2, Media Lab wants to use GPL v3. Nowadays I see examples that let's you pick between MIT and GPU.
