### ISSUE TITLE
get_geogrid_data only on interactive cells

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_Brix#24]
Right now get_geogrid_data is retuning in all cells, I think it should only return on interactive cells or have an option

**Comment by crisjf** [comment]
See commit 68e8f2f6d4abdabfde1ad77130bd32f14786cbd6

**Comment by crisjf** [comment]
![image](https://user-images.githubusercontent.com/8973959/107090944-f407ae00-67ce-11eb-9c26-3285de9a4dbd.png)

https://cityscope.media.mit.edu/CS_Brix/classes.html#handler-class

**Comment by crisjf** [comment]
@guadalupebabio could we get rid of this feature? Now that I think more about it, it's a bit of a slippery slope to implement custom cell filters here. You can always implement it yourself in your module.

**Comment by guadalupebabio** [comment]
Sure! that works I can just make it locally

**Comment by crisjf** [comment]
Ok, so now the way to do it is:

```
H = Handler('dungeonmaster')
geogrid_data = H.get_geogrid_data().remove_noninteractive()
```
