### ISSUE TITLE
`Handler.get_geogrid_data` returns geodataframe without crs

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_Brix#25]
When using `as_df=True` and `include_geometries` I get a GeoDataFrame without crs. 

This is the code:
```
geogrid_data = H.get_geogrid_data(include_geometries=True,as_df=True,exclude_noninteractive=True)
geogrid_data = geogrid_data.set_crs(crs=wgs84)
geogrid_data = geogrid_data.to_crs(local_projection)
```

**Comment by crisjf** [comment]
Fixed! 

It'll be available in version `0.0.7`, but I'll wait for a few more updates to update pip. 

![image](https://user-images.githubusercontent.com/8973959/107552748-ea50c280-6ba1-11eb-9251-f17189e8dad6.png)
