### ISSUE TITLE
New Feature: create graph of grid

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#28]
Build feature that returns a `networkx.Graph` connecting each cells to its nearest neighbors. This will be useful for module builders who want to build modules where cells interact with each other.

**Comment by RELNO** [comment]
very cool feature. this can help many different modules -- how compute intensive you imagine this to be on large grids?

**Comment by crisjf** [comment]
It worked fine on [Guada's grid](https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=lomas), which is pretty large.

It goes fast because grids are never rotated. So if you ever implement the option of having a rotated grid with respect to the lat/lon space, then this will not work anymore.

**Comment by crisjf** [comment]
Here's the code to work with this:

```
H.get_geogrid_data().as_graph()
```

@guadalupebabio this might be useful for your module

I have yet to add it to the docs.

**Comment by crisjf** [comment]
Documentation here:

https://cityscope.media.mit.edu/CS_Brix/classes.html#brix.GEOGRIDDATA.as_graph
