### ISSUE TITLE
Redundancy in geogrid_data as as_df

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#29]
There are now two ways of getting geogrid_data as_df.

Option 1:
```
H = Handler('dungeonmaster')
geogrid_data_df = H.get_geogrid_data(as_df=True)
```

Option 2:
```
H = Handler('dungeonmaster')
geogrid_data_df = H.get_geogrid_data().as_df()
```

We will go with option two because it's more flexible. Option 1 is a wrapper for Option 2 anyways. 

This is an easy code fix, but might change some things in the docs.

**Comment by crisjf** [comment]
Need to go through tutorial.

**Comment by RELNO** [comment]
Question: when it's converted to df, is it recreating the df or only updates its values?

**Comment by crisjf** [comment]
it was, but now it's not

**Comment by crisjf** [comment]
Documentation here:

https://cityscope.media.mit.edu/CS_Brix/classes.html#brix.GEOGRIDDATA.as_df
