### ISSUE TITLE
GEOGRID object in cityio is different across tables

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#30]
For `dungeonmaster`

![image](https://user-images.githubusercontent.com/8973959/109546102-bd544900-7a97-11eb-9c07-fa80b4a555ed.png)

For `lomas`
![image](https://user-images.githubusercontent.com/8973959/109546173-d52bcd00-7a97-11eb-824c-2adbe914581e.png)

The difference is that one has an `id` the other one doesn't. This causes `brix.Handler.get_GEOGRID_EDGES` to fail. I'm gonna implement a try/catch for now, but this is weird.

**Comment by crisjf** [comment]
@RELNO could you take a quick look at this?

**Comment by RELNO** [comment]
first of all, welcome to flickr. 
Second: I'm not 100% why, but in practice the GEOGRID objects properties can grow to include many attributes, but must have only height, color, name, and interactive (if I'm not forgetting something). Is this inconsistency breaks something?

**Comment by crisjf** [comment]
LOL

Could we also keep the id in the GEOGRID object as well? It'll make it much reliable, especially when people build tables with a large non-interactive area. It's not an issue if we don't have it, and we just index the cell by its position in GEOGRID. I just have to remind myself of this.

**Comment by RELNO** [comment]
Yes -- so I've just tested on https://cityio.media.mit.edu/api/table/cityscopejs and ID comes with.

**Comment by crisjf** [comment]
Ok! So moving forward I'll assume GEOGRID also has the id, except for old tables like `dungeonmaster`.

**Comment by crisjf** [comment]
we're good

I recreated `dungeonmaster` and now I see the ids in `GEOGRID`

https://cityio.media.mit.edu/api/table/dungeonmaster/GEOGRID
