### ISSUE TITLE
Numeric and heatmap indicators together

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_Brix#32]
I have a use case with a simulation that needs to post both heatmap and numeric indicators. Is this supported? How should I write the `return_indicator` function?

**Comment by doorleyr** [comment]
I think it's not possible right now but I also have use cases that would benefit from such a capability. 
At the moment I'm using a workaround where I do my own post request inside the return_indicator() function. See the Proximity_Indicator class here:
https://github.com/doorleyr/OpenCity/blob/master/CS_Indicators.py

**Comment by crisjf** [comment]
Very clever. 

I'll work on this, I don't think it's gonna be that complicated.

**Comment by crisjf** [comment]
I started working on this in a new branch:
https://github.com/CityScope/CS_Brix/tree/hybrid_indicators

There's a first commit already, and it seems to be working.

Here's a simple example of a noise indicator that posts noise and average noise:
```
from brix import Indicator
from numpy import mean
import random
class Noise(Indicator):
    '''
    Example of Noise heatmap indicator for points centered in each grid cell.
    The main difference between a heatmap and a numeric indicator is that indicator_type is set to either 'heatmap' or 'access'.

    Note that this class requires the geometry of the table as input, which is why it sets:
    requires_geometry = True
    in the setup.

    '''
    def setup(self,name=None):
        self.indicator_type = 'hybrid'
        self.name = ('noise' if name is None else name)
        self.requires_geometry = True

    def return_indicator(self, geogrid_data):
        features = []
        for cell in geogrid_data:
            feature = {}
            lat,lon = zip(*cell['geometry']['coordinates'][0])
            lat,lon = mean(lat),mean(lon)
            feature['geometry'] = {'coordinates': [lat,lon],'type': 'Point'}
            feature['properties'] = {self.name:random.random()}
            features.append(feature)
        out = {'type':'FeatureCollection','features':features}
        mean_noise = mean([cell['properties'][self.name] for cell in features])
        return {'heatmap':out,'numeric':mean_noise}
```

Note the syntax for the return. It has to be a dict with two keys, `numeric` and `heatmap` (or `access`).

When connected to a Handler like so
```
from brix import Handler
H = Handler('dungeonmaster')
I = Noise()
H.add_indicator(I)
H.update_package()
```

It posts two indicators, a numeric one:
```
[{'value': 0.526540176414777,
  'name': 'noise',
  'indicator_type': 'hybrid',
  'viz_type': 'radar'}]
```

And the noisy access one:
```
{'type': 'FeatureCollection',
 'properties': ['noise'],
 'features': [{'geometry': {'coordinates': [-71.08518949729782,
     42.36628544396724],
    'type': 'Point'},
   'properties': [0.9817324802377755]},
  {'geometry': {'coordinates': [-71.08458249013162, 42.366285441099905],
    'type': 'Point'},
   'properties': [0.2714445176822249]},
  ...
]}
```

**Comment by crisjf** [comment]
Checkout the documentation for this here:

https://cityscope.media.mit.edu/CS_Brix/examples.html#hybrid-indicator

![image](https://user-images.githubusercontent.com/8973959/111004686-75ff6f80-8357-11eb-8890-657c6d72f232.png)

**Comment by doorleyr** [comment]
Looks great. Thanks and sorry for the delayed response.

**Comment by crisjf** [comment]
Merged to master.

94489246d3774eb63f3a4e9316a16a090ae5d8a7
