### ISSUE TITLE
Grid Maker producing incorrect size and rotation of grid

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Brix#42]
Grids created with the Grid() class have incorrect cell size and are flipped vertically.

**Comment by crisjf** [comment]
@doorleyr did you fix this here 7ac74b95241627b69db480a128d3bc1ede2aaf72
or is it still open?

**Comment by doorleyr** [comment]
It should be fixed. @guadalupebabio can reopen if not.
