### ISSUE TITLE
New error when running Handler.listen(). Seems to be related to unlinked indicators

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Brix#45]
Since upgrading to the latest release of brix, I get the following error with all of my indicators which were working before.
```
   1311                 unlinked_indicators = self.list_unlinked_indicators()
   1312                 if len(unlinked_indicators)>0:
-> 1313                         unlinked_indicators = ', '.join(unlinked_indicators)
   1314                         warn(f'You have unlinked indicators: {unlinked_indicators}')
   1315                 self.append_on_post = append

TypeError: sequence item 0: expected str instance, NoneType found
```
Here's the notebook I'm using: https://github.com/doorleyr/OpenCity/blob/master/CS_Indicators_example.ipynb

I have several indicators I'm working with and I have tried adding just one of them or all of them, using add_indicator() or add_indicators() but I now always get this error when I run H.listen()

**Comment by crisjf** [comment]
Did you define `self.name` for your indicators in `setup`? This might be the issue.

If this was the issue, it will be gone in version `0.0.10`, but for now, just name them and it should disappear.

If this was not the issue, let me know and I'll look into it.

**Comment by crisjf** [comment]
Yeah, this seems to have been fixed in this commit:
ca9176fe02de6bd7a71fc98b9237212ca17fcebb

which happened the day after we pushed `0.0.9`

I'll update to `0.0.10` sometime next week. I was waiting for #34 to be done and it seems we have converged to a stable solution.

**Comment by doorleyr** [comment]
Setting a name worked. Thanks @crisjf

**Comment by crisjf** [comment]
Awesome!
