### ISSUE TITLE
Numeric indicators not showing on front end

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Brix#5]
The indicators are properly posted in:
https://cityio.media.mit.edu/api/table/dungeonmaster/indicators

![image](https://user-images.githubusercontent.com/8973959/92276758-9ee20c00-eebf-11ea-9ea6-6a2415d88a66.png)

But they don't show up in 
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=dungeonmaster
![image](https://user-images.githubusercontent.com/8973959/92276780-aa353780-eebf-11ea-8d48-25cc2b917d7a.png)

Is there an issue with the format they were posted it?

**Comment by RELNO** [comment]
Looking at the log: 

<img width="470" alt="Screen Shot 2020-09-04 at 15 32 25" src="https://user-images.githubusercontent.com/14296774/92278764-e2d71000-eec3-11ea-8851-07ae02d9913c.png">

it seems you're maybe misfeed/partially feeding the visualizer with all necessary data. Can you aim to comply with  https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=corktown  / https://cityio.media.mit.edu/api/table/corktown/indicators?

**Comment by crisjf** [comment]
That makes sense! `viz_type` is missing. I'll make sure to note that on the `README` as well.
